# Generated by Django 2.1.8 on 2019-09-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0003_auto_20190919_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='payorder',
            name='order_status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
