# Generated by Django 2.1.8 on 2019-09-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_number', models.CharField(max_length=11)),
                ('goods_name', models.CharField(max_length=32)),
                ('goods_price', models.FloatField()),
                ('goods_count', models.IntegerField()),
                ('goods_location', models.CharField(max_length=256)),
                ('goods_safedate', models.IntegerField()),
                ('goods_manufacturedate', models.DateField(auto_now=True)),
                ('goods_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=32, null=True)),
                ('photo', models.ImageField(default='images/default.png', upload_to='images')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=32, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
