# Generated by Django 2.1.8 on 2019-09-09 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_auto_20190909_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodstype',
            old_name='type_lable',
            new_name='type_label',
        ),
    ]
