# Generated by Django 2.1.8 on 2019-09-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0004_auto_20190909_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='picture',
            field=models.ImageField(default='static/banner05.jpg', upload_to='images'),
            preserve_default=False,
        ),
    ]
