"""
Django settings for Shopsys project.

Generated by 'django-admin startproject' using Django 2.1.8.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'h&ye^gt1dig+rw8b^)z$sy13eri_6$h%f%)c2e5i)c+=agcwhh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Buyer',
    'Seller',
    'djcelery',
]

MIDDLEWARE = [
    'django.middleware.cache.UpdateCacheMiddleware',#全站缓存
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'Retailers.middleware.MiddleWareTest',
    'django.middleware.cache.FetchFromCacheMiddleware',#全站缓存
]

ROOT_URLCONF = 'Retailers.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Retailers.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# STATIC_ROOT=os.path.join(BASE_DIR,'static')#静态文件的根目录，和STATICFILES_DIRS，MEDIA_URL，MEDIA_ROOT有冲突

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'static')

alipay_public_key_string = '''-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAthIIFxUu1p4k9/Eydm3CSTGRKlSmXtselygI1izhbSRYtjs1IS2rYxr9UWT9N2fWDM3GN75SEMYwRHBj+d0/7rhzTi3eGIv/5h49oiJWbltd4rCiDfrxfythtS88oRXOgV3Tc9bIMjhy9u8mbt+MUP8KRu/zY6W1TQa2dYOE6GxG1MGvYHBcPK8YNyBS/REY5FKwARDh/l/xonpbyJ+lvmPdRZIfJ8uCkHGJz2rLet1psve65YGaaEllcZrUhGSjS/HXTJiu/y+FWuX4LxhO8UQssjL8txZWIUk9ASkCyfk91O34Njs9C4t69niFDEGGZ0uiAXHKj/mhoyqVCRC0JwIDAQAB
-----END PUBLIC KEY-----'''

alipay_private_key_string = '''-----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEAthIIFxUu1p4k9/Eydm3CSTGRKlSmXtselygI1izhbSRYtjs1IS2rYxr9UWT9N2fWDM3GN75SEMYwRHBj+d0/7rhzTi3eGIv/5h49oiJWbltd4rCiDfrxfythtS88oRXOgV3Tc9bIMjhy9u8mbt+MUP8KRu/zY6W1TQa2dYOE6GxG1MGvYHBcPK8YNyBS/REY5FKwARDh/l/xonpbyJ+lvmPdRZIfJ8uCkHGJz2rLet1psve65YGaaEllcZrUhGSjS/HXTJiu/y+FWuX4LxhO8UQssjL8txZWIUk9ASkCyfk91O34Njs9C4t69niFDEGGZ0uiAXHKj/mhoyqVCRC0JwIDAQABAoIBAQCvwAwrK/mAljudUyihBSZMPRqhwACxA9ctlimhhMU9853mmpSYqFsOWZk5nsCHYSZQSboTSRYytv0Us2DuatIx/77eMox3KX0lhv97qKXB9VRVZKep0xiW5yt0GFrwK/qhCg75fNTXFYJ0NznkQMpTzT0AaNOK1wSBi/9IxGHhcDGL1oqpJGu1VuKAWHkaSZIJovOCHKErCUt0tVYRojw1Hn+i5TjKbte4ptmxU1iugacA9avv0Q6ZWGTPk9R52AAeAtQa3E1sHdk0Bl83yKJBymuzTHnsJ3L2T2WALMvzD/rVo1YrOR4c+0ZrcDMKryMCTXxVvq8lr241aKx64/xxAoGBAOk0MXqNLD2G+QBcTZHoTGFkdvzeZ9CV7E9fsPp8vGPLQRAjefqLYWJuKo7KGDZL3qVWSKAOp/npSi8wgZv+0E3nDiF+DEOS4lvMlkulzYcLeqWjKGVdyT0cOKGbqbWWCHExcRlW5KOAPpiI+BaeWXKf2TvF56tcDeTe898y0DgLAoGBAMfeQBKCxgnnIHK+9ktUB/7L+NCddbwla7+6ilaHRGkZi0RTd90yZsxtOizufsW0Ixupiyij9IstN8qvnk6meAHQdD2Ga0zzMiIklv7UH6SsecMF+ePFhQKP0L5L7/XNuvRzhJeoL2X9P624mvFy178FG6DSwlvaSwMu30EXqxnVAoGBAN6ujCCt9XS7EcIaYafV3jmRqV1FMnSm9IPGqERIH8xbJcG3Xp6zwUYwVEsNB5mxUOUoQykzVYr6DXCKLPk8lMQOwhuRNTzBYYyvC0UpCdzORUstRUGmEKdd72XCMofGwED2KT09EA5gQ2V8RQm0I02k/dZp4BJtUIcfrlePOeyJAoGBAMJkElMup+inyDJyMuAu+ZvCzNwx2XnFt5eBmdzwsQO7mW059WHJDJyVO7jJubkWK/NSogtD86uNri7PQhxi4mN5WCUi4Ke1/TOh/M4aiDBEpCSfYl07FdPZBoCfIOMkVko9NF/Ab2E1v8J5wxFEzjt2f1mawvhNRxnwc6k+mOaFAoGAYOAkC8ra1pEPu3xAN+kWOKI1vXx+6AQolln77TprFdvvkdquyxneT8nPtfUnxTaahIrAmC/0laaNis3OpZ4SiQFyxwiuMRR7nz2N39XEb2pH+wOvUY/bdYJW7ZHT+e6BdMklI96VY+SNQ7UKWA77WKNypCg9S6AN9Y9KIj/uXcs=
-----END RSA PRIVATE KEY-----'''

DING_URL = 'https://oapi.dingtalk.com/robot/send?access_token=145ea7ffff1fcc9ef0ad292a427e634f3fba67c7a5478fedca1e7d2422df6aa7'

import djcelery  # 导入django-celery模块

djcelery.setup_loader()  # 模块加载
BROKER_URL = 'redis://127.0.0.1:6379/1'  # 任务容器地址，redis数据库地址
CELERY_IMPORTS = ('CeleryTask.tasks')  # 具体任务文件
CELERY_YIMEZONE = 'Asia/Shanghai'  # celery时区
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'  # celery处理器，固定

# 计时任务
from celery.schedules import crontab, timedelta

CELERYBEAT_SCHEDULE = {
    u'测试': {
        'task': 'CeleryTask.tasks.add',  # 任务函数
        'schedule': timedelta(seconds=5)  # 执行时间
    }
}

ERROR_PATH = os.path.join(BASE_DIR, 'error.log')

# The cache backends to use.
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
#         'LOCATION':[
#             '127.0.0.1:11211'#本地memcache的地址端口
#         ]
#     }
# }
# CACHE_MIDDLEWARE_KEY_PREFIX = ''
# CACHE_MIDDLEWARE_SECONDS = 600
# CACHE_MIDDLEWARE_ALIAS = 'default'

#
# LOGGING={
#     'varsion':1,
#     'disable_existing_logger':False,#是否禁用之前日志
#     'handlers':{
#         'file':{
#             'level':'DEBUG',
#             'class':'logging.FileHandler',
#             'filename':os.path.join(BASE_DIR,'django.log')
#         }
#     },
#     'loggers':{
#         'django':{
#             'handlers':['file'],
#             'level':'DEBUG',
#             'pronagate':True
#         }
#     }
# }


